[package]
name = "cosette"
version = "0.1.0"
authors = ["Shuxian Wang <wsx@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
z3 = { git = "https://github.com/wsx-ucb/z3.rs", branch = "add-binding" }
scopeguard = "1.1"
itertools = "0.10"
permutation = "0.2"
paste = "1.0"
indenter = "0.3"
log = "0.4"
env_logger = "0.9"
imbl = { git = "https://github.com/jneem/imbl", branch = "main" }
anyhow = "1.0"
num = "0.4"
crossbeam = "0.8"
isoperm = { git = "https://github.com/Sicheng-Pan/isoperm", branch = "master" }
